<a href="https://colab.research.google.com/github/Lidiya-cutie/DS_SkillFactory/blob/main/WineDateTime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# РАЗБОР ДАТЫ И ВРЕМЕНИ НА ПРИМЕРЕ ВИННЫХ ОБЗОРОВ

Скачать датасет можно [здесь](https://drive.google.com/file/d/1fuaFlWH881N8KCO_23K_a-5fcm2SICFn/view?usp=share_link)

In [1]:
# Импортируем необходимую библиотеку:
import pandas as pd
# Прочитаем наш файл с винными обзорами:
data = pd.read_csv('wine_cleared.zip')

Признаки, обозначающие дату и время, могут содержать много полезной информации. 

Например, в нашем датасете в названии вина можно увидеть год производства вина. Этот признак может оказаться важным для определения рейтинга вина. Однако, пока он заключен в названии вина, модель не сможет его использовать.

Можно выделить год, месяц и часы в отдельные признаки: время суток, времена года и так далее.

## РАЗБОР ЧИСЛОВЫХ ВЕЛИЧИН

В наборе данных очень часто встречаются числовые величины. Это могут быть вес, рост, расстояние и так далее. Вы можете преобразовывать их, создавать новые признаки, которые могут оказаться лучше исходных.

Например, в датасете винных обзоров числовым признаком является цена за бутылку вина. Вы можете округлить цену 35.363389$ в 35$, избавив данные от лишней информации.

✍️ Создадим новый признак price_round, означающий округлённую до целого числа цену за бутылку вина:

In [3]:
# для удобства сразу преобразуем признак в int
data['price_round'] = data['price'].round().astype(int)
data

,Unnamed: 0,country,description,designation,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery,price_round
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,35.363389,Sicily & Sardinia,Etna,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,35
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.000000,Douro,unknown,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,15
2,2,US,"Tart and snappy, the flavors of lime flesh and...",unknown,87,14.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,14
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.000000,Michigan,Lake Michigan Shore,Alexander Peartree,unknown,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,13
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.000000,Mosel,unknown,Anna Lee C. Iijima,unknown,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),28
129967,129967,US,Citation is given as much as a decade of bottl...,unknown,90,75.000000,Oregon,Oregon,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,75
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,30
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",unknown,90,32.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,32
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,21

Для таких преобразований важен контекст. В контексте вина для сомелье цена в 35$ и 35.363389$ одинакова. Вы делаете округление признака, чтобы модель также не сосредотачивалась на сотых. Это может помочь улучшить предсказание.

Однако такое преобразование неуместно в ситуациях, когда сотые важны. Например, при предсказании курса лиры стоимость валюты в 6.12 руб. и в 6.84 руб. — абсолютно разные ситуации.

Помимо округления для создания новых признаков могут применяться такие популярные операции, как логарифмирование числового признака или извлечение его корня. Это подразумевает создание признаков в наиболее удобной форме для обучения модели. О необходимости таких преобразований вы узнаете далее в юните преобразования данных.

## РАЗБОР ТЕКСТА

Текстовые признаки могут содержать в себе большое количество информации. Например, если бы наша модель умела распознавать текст, то из описания вина мы бы могли понять, какими словами сомелье чаще характеризуют качественное вино. Вы можете воспользоваться методами извлечения слов из текста, чтобы получить новые признаки.

В названии вина вы можете заметить указание года произведения вина. Чтобы узнать, влияет ли год на рейтинг вина, вам необходимо выделить год в отдельный признак.

Для того, чтобы извлечь из строки число, обозначающее год, необходимо воспользоваться **регулярными выражениями**.

**Регулярные выражения** (*regexp*, или *regex*) — это механизм для поиска и замены текста. Это шаблоны, которые используются для поиска соответствующей части текста.

Например, с помощью такого регулярного выражения [^@\t\r\n]+@[^@\t\r\n]+\.[^@ \t\r\n]+ можно найти любой email в тексте.

*Демонстрацию работы регулярного выражения для поиска email в тексте можно посмотреть в [источнике](https://ihateregex.io/playground/)*

Синтаксис регулярных выражений необычен и содержит различные символы, знаки препинания, математических операций и так далее. Подробнее ознакомиться с синтаксисом регулярных выражений поможет статья [Python RegEx: практическое применение регулярок](https://tproger.ru/translations/regular-expression-python/).

Реализация такого механизма существует в *pandas* в работе со строками. Для того чтобы найти все числа в каждом значении серии, воспользуемся методом [str.findall()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.findall.html). Метод возвращает все совпадения с заданным шаблоном в серии *pandas*.

✍️ Выполните код для нахождения года вина при помощи регулярного выражения:

In [5]:
# регулярное выражение для нахождения чисел
regex = '\d{4}'
data['year'] = data['title'].str.findall(regex).str.get(0)
data

,Unnamed: 0,country,description,designation,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery,price_round,year
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,35.363389,Sicily & Sardinia,Etna,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,35,2013
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.000000,Douro,unknown,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,15,2011
2,2,US,"Tart and snappy, the flavors of lime flesh and...",unknown,87,14.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,14,2013
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.000000,Michigan,Lake Michigan Shore,Alexander Peartree,unknown,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,13,2013
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,65,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.000000,Mosel,unknown,Anna Lee C. Iijima,unknown,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),28,2013
129967,129967,US,Citation is given as much as a decade of bottl...,unknown,90,75.000000,Oregon,Oregon,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,75,2004
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,30,2013
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",unknown,90,32.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,32,2012
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,21,2012

Разберём регулярное выражение *\d{4}*:

* \d — класс символов, обозначает соответствие цифрам в диапазоне цифр [0-9];
* {4} в шаблоне означает **искать четыре вхождения символа, указанного ранее**. В нашем случае это будут четырехзначные числа.

Таким образом, *\d{4}* означает поиск четырехзначных чисел в заданной строке.

Проверить, насколько точно работает ваше регулярное выражение, а также найти реализацию популярных регулярных выражений (например, поиска номера телефона), вы сможете на сайте https://ihateregex.io.

Однако при поиске числа методом *data['title'].str.findall(regex)* результатом выполнения является список найденных цифр. Поэтому необходимо извлечь первый элемент из списка найденных методом *str.get(0)*, где 0 — первый элемент в списке найденных чисел.

Используя методы работы со строками pandas и регулярные выражения, можно извлечь любую информацию для новых признаков: даты, слова и выражения.

## РАЗБОР КАТЕГОРИЙ

В наборе данных винных обзоров самая популярная страна-производитель вина — США. Возможно, это не случайность, и факт производства в США влияет на рейтинг вина. Выделим этот факт.

Вы можете создать новый бинарный признак *is_usa* и присвоить ему 1 в случае, если вино произведено в США, иначе — 0.

In [8]:
data['is_usa'] = data['country'].apply(lambda x: 1 if x == 'US' else 0)
data

129908

В наборе данных также есть ещё две страны, которые являются не менее популярными производителями вина. Их можно найти следующим способом:

In [14]:
data.groupby(['country']).count()

,Unnamed: 0,description,designation,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery,price_round,year,is_usa
country,,,,,,,,,,,,,,,
Argentina,3800,3800,3800,3800,3800,3800,3800,3800,3800,3800,3800,3800,3800,3755,3800
Armenia,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Australia,2329,2329,2329,2329,2329,2329,2329,2329,2329,2329,2329,2329,2329,2260,2329
Austria,3345,3345,3345,3345,3345,3345,3345,3345,3345,3345,3345,3345,3345,3304,3345
Bosnia and Herzegovina,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Brazil,52,52,52,52,52,52,52,52,52,52,52,52,52,41,52
Bulgaria,141,141,141,141,141,141,141,141,141,141,141,141,141,141,141
Canada,257,257,257,257,257,257,257,257,257,257,257,257,257,256,257
Chile,4472,4472,4472,4472,4472,4472,4472,4472,4472,4472,4471,4472,4472,4445,4472
China,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Croatia,73,73,73,73,73,73,73,73,73,73,73,73,73,72,73
Cyprus,11,11,11,11,11,11,11,11,11,11,11,11,11,10,11
Czech Republic,12,12,12,12,12,12,12,12,12,12,12,12,12,11,12
Egypt,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
England,74,74,74,74,74,74,74,74,74,74,74,74,74,60,74
France,22093,22093,22093,22093,22093,22093,22093,22093,22093,22093,22093,22093,22093,20511,22093
Georgia,86,86,86,86,86,86,86,86,86,86,86,86,86,84,86
Germany,2165,2165,2165,2165,2165,2165,2165,2165,2165,2165,2165,2165,2165,2149,2165
Greece,466,466,466,466,466,466,466,466,466,466,466,466,466,445,466
Hungary,146,146,146,146,146,146,146,146,146,146,146,146,146,143,146
India,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Israel,505,505,505,505,505,505,505,505,505,505,505,505,505,504,505
Italy,19540,19540,19540,19540,19540,19540,19540,19540,19540,19540,19540,19540,19540,18550,19540
Lebanon,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35
Luxembourg,6,6,6,6,6,6,6,6,6,6,6,6,6,3,6
Macedonia,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Mexico,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70
Moldova,59,59,59,59,59,59,59,59,59,59,59,59,59,57,59
Morocco,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28
New Zealand,1419,1419,1419,1419,1419,1419,1419,1419,1419,1419,1419,1419,1419,1409,1419
Peru,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Portugal,5691,5691,5691,5691,5691,5691,5691,5691,5691,5691,5691,5691,5691,5374,5691
Romania,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120
Serbia,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Slovakia,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Slovenia,87,87,87,87,87,87,87,87,87,87,87,87,87,85,87
South Africa,1401,1401,1401,1401,1401,1401,1401,1401,1401,1401,1401,1401,1401,1386,1401
Spain,6645,6645,6645,6645,6645,6645,6645,6645,6645,6645,6645,6645,6645,6142,6645
Switzerland,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Turkey,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90
US,54504,54504,54504,54504,54504,54504,54504,54504,54504,54504,54504,54504,54504,53585,54504
Ukraine,14,14,14,14,14,14,14,14,14,14,14,14,14,5,14
Uruguay,109,109,109,109,109,109,109,109,109,109,109,109,109,108,109

Создав бинарные признаки is_france, is_italy наподобие признака is_usa, можно убедиться в прпавильности когда выше, вычислив сумму по признакам is_italy и is_france:

In [16]:
data['is_france'] = data['country'].apply(lambda x: 1 if x == 'France' else 0)
data['is_italy'] = data['country'].apply(lambda x: 1 if x == 'Italy' else 0)
data['is_france'].sum(), data['is_italy'].sum()

(22093, 19540)

Попробуем вывести правило в определении качества вина: старые вина лучше молодых. В нашем датасете 40 % вин старше 2010 года.

Cоздайте новый бинарный признак old_wine, где значение 1 будет обозначать, что вино старше 2010 года.

In [19]:
data['old_wine'] = data['year'].apply(lambda x: 1 if float(x) < 2010 else 0)
data['old_wine'].sum()

39781

Таким образом, разбор категорий, даты и времени, числовых признаков, текста применяются для создания новых, более сильных признаков для обучения.

In [59]:
# регулярное выражение для нахождения словa в круглых скобках
regexp = '.*?\(([^)]*)\).*'
data['locality'] = data['title'].str.findall(regexp).str.get(-1)
data

,Unnamed: 0,country,description,designation,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery,price_round,year,is_usa,is_france,is_italy,old_wine,locality
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,35.363389,Sicily & Sardinia,Etna,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,35,2013,0,0,1,0,Etna
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.000000,Douro,unknown,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,15,2011,0,0,0,0,Douro
2,2,US,"Tart and snappy, the flavors of lime flesh and...",unknown,87,14.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,14,2013,1,0,0,0,Willamette Valley
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.000000,Michigan,Lake Michigan Shore,Alexander Peartree,unknown,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,13,2013,1,0,0,0,Lake Michigan Shore
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,65,2012,1,0,0,0,Willamette Valley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.000000,Mosel,unknown,Anna Lee C. Iijima,unknown,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),28,2013,0,0,0,0,Erben Müller-Burggraef
129967,129967,US,Citation is given as much as a decade of bottl...,unknown,90,75.000000,Oregon,Oregon,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,75,2004,1,0,0,1,Oregon
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,30,2013,0,1,0,0,Alsace
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",unknown,90,32.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,32,2012,0,1,0,0,Alsace
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,21,2012,0,1,0,0,Alsace